// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5o1Dbrcer48b2uWztEu0-1hO1AH_QLzA',
    appId: '1:736859027312:web:37cf10b3f17f2e26c201b5',
    messagingSenderId: '736859027312',
    projectId: 'mentalhealth-8e1e9',
    authDomain: 'mentalhealth-8e1e9.firebaseapp.com',
    databaseURL: 'https://mentalhealth-8e1e9-default-rtdb.firebaseio.com',
    storageBucket: 'mentalhealth-8e1e9.firebasestorage.app',
    measurementId: 'G-MF9LYLDMEX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKKYbx1kqCUHT4DOQss-WpsCfCJ--FM4Q',
    appId: '1:736859027312:android:8b5a0a26ad1cb882c201b5',
    messagingSenderId: '736859027312',
    projectId: 'mentalhealth-8e1e9',
    databaseURL: 'https://mentalhealth-8e1e9-default-rtdb.firebaseio.com',
    storageBucket: 'mentalhealth-8e1e9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrpqPvKqQvhUIlU_topIaOFLVZM13Yl8w',
    appId: '1:736859027312:ios:f53822daeb88f3e1c201b5',
    messagingSenderId: '736859027312',
    projectId: 'mentalhealth-8e1e9',
    databaseURL: 'https://mentalhealth-8e1e9-default-rtdb.firebaseio.com',
    storageBucket: 'mentalhealth-8e1e9.firebasestorage.app',
    iosBundleId: 'com.example.mentalHealth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrpqPvKqQvhUIlU_topIaOFLVZM13Yl8w',
    appId: '1:736859027312:ios:f53822daeb88f3e1c201b5',
    messagingSenderId: '736859027312',
    projectId: 'mentalhealth-8e1e9',
    databaseURL: 'https://mentalhealth-8e1e9-default-rtdb.firebaseio.com',
    storageBucket: 'mentalhealth-8e1e9.firebasestorage.app',
    iosBundleId: 'com.example.mentalHealth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5o1Dbrcer48b2uWztEu0-1hO1AH_QLzA',
    appId: '1:736859027312:web:a0588c2c221fcfb9c201b5',
    messagingSenderId: '736859027312',
    projectId: 'mentalhealth-8e1e9',
    authDomain: 'mentalhealth-8e1e9.firebaseapp.com',
    databaseURL: 'https://mentalhealth-8e1e9-default-rtdb.firebaseio.com',
    storageBucket: 'mentalhealth-8e1e9.firebasestorage.app',
    measurementId: 'G-GCSY66PD3V',
  );
}
